# Generated by Django 2.1.1 on 2018-09-24 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adfacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='in_support_of',
            new_name='candidate_or_initiative',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='opposing',
        ),
        migrations.AddField(
            model_name='ad',
            name='district',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='format',
            field=models.CharField(blank=True, choices=[('mailer', 'Mailer'), ('tv', 'TV'), ('radio', 'Radio'), ('youtube', 'Youtube'), ('fb', 'Facebook'), ('email', 'Email'), ('yard_sign', 'Yard Sign'), ('large_sign', 'Large Sign'), ('other', 'Other')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='race',
            field=models.CharField(blank=True, choices=[('', ''), ('gov', 'Governor'), ('sec_of_state', 'Secretary of State'), ('atty_gen', 'Attorney General'), ('treasurer', 'Treasurer'), ('corp_comm', 'Corporation Commissioner'), ('state_house', 'State House'), ('state_senate', 'State Senate'), ('ballot_init', 'Ballot Initiative'), ('other', 'Other')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='support_oppose',
            field=models.CharField(choices=[('for', 'For'), ('against', 'Against')], default='for', max_length=32),
        ),
        migrations.AddField(
            model_name='org',
            name='dark_money',
            field=models.CharField(choices=[('y', 'Y'), ('n', 'N')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='location',
            field=models.CharField(choices=[('arizona', 'Arizona'), ('out_of_state', 'Out Of State'), ('unknown', 'Unknown')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='org_type',
            field=models.CharField(choices=[('501c4', '501c4'), ('PAC', 'PAC'), ('other', 'Other')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adfacts.Org'),
        ),
        migrations.AlterField(
            model_name='org',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='org',
            name='sos_link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
