# Generated by Django 2.1.1 on 2018-09-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adfacts', '0003_auto_20180926_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='donors',
            field=models.ManyToManyField(blank=True, to='adfacts.Donor'),
        ),
    ]
