# Generated by Django 2.1.1 on 2018-09-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adfacts', '0004_auto_20180926_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='district',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
