# Generated by Django 2.1.1 on 2018-09-26 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adfacts', '0005_auto_20180926_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='candidate_or_initiative',
            field=models.CharField(max_length=256, verbose_name='Candidate or Initiative Number'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adfacts.Org', verbose_name='Paid For By'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='race',
            field=models.CharField(blank=True, choices=[('', ''), ('ballot_init', 'Ballot Initiative'), ('gov', 'Governor'), ('sec_of_state', 'Secretary of State'), ('atty_gen', 'Attorney General'), ('treasurer', 'Treasurer'), ('corp_comm', 'Corporation Commissioner'), ('state_house', 'State House'), ('state_senate', 'State Senate'), ('super_ed', 'Superintendent of Public Instruction'), ('other', 'Other')], max_length=64, null=True),
        ),
    ]
